config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'

  resources :groups do
    resources :members
  end

  resources :memberships do
    resources :tasks
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, dependent: :destroy
  has_many :tasks, through: :memberships, dependent: :destroy
end

app/models/member.rb
class Member < ActiveRecord::Base
  # I think we've talked about this a bit, but I think this model could be entirely replace with the devise user model.
  # Unless the thought process was that this was completely an administrative only tool. But I think that limits scalability
  # Actually the more I think about it, I think its completely dependent on the domain model you're going for. Maybe you do want to use devise strictly just for auth.
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships, dependent: :destroy
  has_many :tasks, through: :memberships, dependent: :destroy
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member
  belongs_to :group
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :membership
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # this looks great
  def index
    @groups = Group.all
    @group = Group.new
  end

  def create
    @group = Group.create!(group_params)
    redirect_to(groups_path)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end

  def destroy
      @group = Group.find(params[:id])
      @group.destroy
      redirect_to groups_path
    end

  private
  def group_params
    params.require(:group).permit(:title, :photo_url)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @memberships = @group.memberships
    @member = Member.new
    @task = Task.new
  end

  def create
    @group = Group.find(params[:group_id])
    # I didn't know you could do this. Does this create a row in the memberships table then?
    @member = @group.members.create(member_params)
    redirect_to group_members_path(@group)
  end

  def edit
    @group = Group.find(params[:group_id])
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to group_members_path
  end

  def destroy
    @member = Member.find(params[:id])
# yeah i'm still not sure why dependent destroys make it error when you destroy just the member.
    @member.memberships.each do |membership|
      membership.tasks.destroy_all
      membership.destroy
    end
    @member.destroy
    redirect_to group_members_path
  end


  private
  def member_params
    params.require(:member).permit(:name, :image_url)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # :+1:
  def new
    @task = Task.new
    @memberships = Membership.find(params[:membership_id])
    @group = @memberships.group
  end

  def create
    @memberships = Membership.find(params[:membership_id])
    @task = @memberships.tasks.create!(task_params)
    @group = @memberships.group
    redirect_to group_members_path(@group)
  end

  def edit
    @memberships = Membership.find(params[:membership_id])
    @group = @memberships.group
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    memberships = Membership.find(params[:membership_id])
    group = memberships.group
    redirect_to group_members_path(group)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    memberships = Membership.find(params[:membership_id])
    group = memberships.group
    redirect_to group_members_path(group)
  end

  private
  def task_params
    params.require(:task).permit(:task, :due_by)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>
  <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<div class= 'new_edit'>
  <h2>Edit Group</h2>

  <%= render 'form' %>
  <p><%= link_to 'Cancel', groups_path%></p>
</div>

app/views/groups/index.html.erb
<div class = 'group_heading'>
  <h2>Groups</h2>
    <% if current_user %>
      <p><%= render 'form' %>
    <% end%>
</div>

  <% @groups.each do |group| %>
  <div class = 'groups'>
    <h2> <%= link_to group.title, group_members_path(group) %> </h2>
    <p> <%= link_to image_tag(group.photo_url, size: "150x150"), group_members_path(group) %></p>
      <% if current_user %>
        <%= link_to "Edit", edit_group_path(group) %>
        <%= link_to "Delete", group_path(group), method: :delete %>
      <% end%>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class='header'>
  <h1>Welcome to Taskager</h1>
  <% if current_user %>
    <p></p>
  <% else %>
    <p>Please sign in to edit and create</p>
  <% end%>
    <%= link_to 'Home', groups_path %>
    <% if current_user %>
      <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to 'Signup', new_user_registration_path %> <%= link_to 'Login', new_user_session_path %>
    <% end %>
</header>

  <%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for [@group, @member] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/members/edit.html.erb
<div class= 'new_edit'>
  <h2>Edit Member</h2>

  <%= render 'form' %>
  <p><%= link_to 'Cancel', group_members_path(@group)%></p>
</div>

app/views/members/index.html.erb
<div class='member_heading'>
  <h2><%= @group.title %> Members</h2>
    <% if current_user %>
      <p><%= render 'form' %>
    <% end%>
      <%= link_to "Return to Groups", groups_path%></p>
</div>

  <% @memberships.each do |membership| %>
  <div class= 'members'>
    <div class= 'member_title'>
      <h2><%=membership.member.name %> </h2>
    </div>
    <div class= 'member_links'>
      <% if current_user %>
        <%= link_to "Edit", edit_group_member_path(@group, membership.member) %>
        <%= link_to "Delete", group_member_path(@group, membership.member), method: :delete %>
      <% end%>
    </div>
    <p><%= link_to "Add Tasks", new_membership_task_path(membership) %></p>

      <ul><% membership.tasks.each do |task| %>
        <div class='task_list'>
          <li><%=task.task%>
            <% if current_user %>
              <%= link_to "Edit", edit_membership_task_path(membership, task) %>
              <%= link_to "Delete", membership_task_path(membership, task), method: :delete %>
            <% end%>
            <ul>
              <li>Due by: <%=task.due_by%> </li>
            </ul>
          </li>
        </div>
          <%end%>
      </ul>
    </div>
      <%end%>

app/views/tasks/_form.html.erb
<%= form_for [@memberships, @task] do |f| %>
  <%= f.label :task %>
  <%= f.text_field :task %>
  <%= f.label :due_by %>
  <%= f.text_field :due_by %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class= 'new_edit'>
  <h2>Edit Task</h2>

  <%= render 'form' %>
  <p><%= link_to 'Cancel', group_members_path(@group)%></p>
</div>

app/views/tasks/new.html.erb
<div class= 'new_edit'>
  <h2>New Task</h2>

  <%= render 'form' %>
  <p><%= link_to 'Cancel', group_members_path(@group)%></p>
</div>